# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BannerDemo' do

pod 'KJBannerView'  # 轮播图，网络图片加载

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BannerDemo
  
  ##################加入代码##################
  # 使用第三方库xcode报错Cannot synthesize weak property because the current deployment target does not support weak references
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
  ##################加入代码##################

  target 'BannerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BannerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
